[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
    ESP32Async/ESPAsyncWebServer @ ^3.1.0
    ESP32Async/AsyncTCP @ ^3.2.0
    links2004/WebSockets @ ^2.6.1

build_flags =
    -DCORE_DEBUG_LEVEL=0